### ISSUE TITLE
Color Identifier

### ISSUE THREAD

**Issue by Mysterious-Owl** [metafy-social/py-scripts#21]
### Is your feature request related to a problem? Please describe
A GUI application which can browse an image and tell you color name and HEX code for the cursor position/pin. GUI with random themes

### Describe the solution you'd like
a GUI application

**Comment by Abubakrce19** [comment]
Please assign me this one.
Thank you

**Comment by bartick** [comment]
@Mysterious-Owl please start working. I am having a mac issue after the new macOs 12.6 update. I will assign it to you as soon as my laptop is fixed. 

Also if you are done don't hesitate to open a PR
